### ISSUE TITLE
Memory Peak Bug and Middlescroll Is Kind of Broken

### ISSUE THREAD

**Issue by aaaproooo** [hironothilo/FNF-HIRO-PROJECT#5]
### Describe your bug here.

Like Mem now is 696 MB but when Mem is Lower Than That Like 555 MB Mem Peak is 555 MB
and MiddleScroll is Buggy
![AAAAAAAAAA](https://user-images.githubusercontent.com/89444135/197920862-f6bd08f7-6d81-425d-9343-8da3e583ff46.png)
![Bug](https://user-images.githubusercontent.com/89444135/197920865-533faad9-27f3-4038-8f18-577a2103ff38.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by aaaproooo** [comment]
Forgot to Say that I downloaded it from GitHub Action not Source Code

**Comment by hironothilo** [comment]
ok now i will fix this bug.
