### ISSUE TITLE
When Click Enter after Resultscreen Finish Something Wrong Here IDK How to describe that

### ISSUE THREAD

**Issue by aaaproooo** [hironothilo/FNF-HIRO-PROJECT#6]
https://user-images.githubusercontent.com/89444135/200308133-c308179d-e560-4a46-b246-4a35ff8d2478.mp4

### Describe your bug here.

Here Bug in Video

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by APRO716** [comment]
https://user-images.githubusercontent.com/89444135/200307928-4589874b-57d4-4781-a8b7-207f7362056f.mp4

**Comment by aaaproooo** [comment]
Latest Commit in This Build BTW I Know this is Test Feature XD https://github.com/hironothilo/FNF-HIRO-EDITION/commit/87dca7497c4519c6554c689a758150ea804ea716

**Comment by aaaproooo** [comment]
ok fine i will close it , we met each other in school and tell it's a feature not a bug lmao
